name: .NET Core CI

on: [push, pull_request]

jobs:
  buildAndTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656
    - name: Build and test with dotnet
      working-directory: src
      run: |
        dotnet build --configuration Release
        dotnet test
